const KEY='pogoTracker_v1';
const TARGET_KEY='pogoTargets_v1';
const defaultTargets={normal:1025,shiny:1025,shadow:1025,regional:120,xxl:1025,xxs:1025,male:1025,female:1025,lucky:1025,fourStar:1025};
const regions=[['Kanto',1,151],['Johto',152,251],['Hoenn',252,386],['Sinnoh',387,493],['Unova',494,649],['Kalos',650,721],['Alola',722,809],['Galar',810,898],['Paldea',906,1025]];
let pokemon=[], collection=load(KEY)||{}, targets=load(TARGET_KEY)||defaultTargets;
function load(k){try{return JSON.parse(localStorage.getItem(k))}catch{return null}}
function save(){localStorage.setItem(KEY,JSON.stringify(collection))}
function saveTargets(){localStorage.setItem(TARGET_KEY,JSON.stringify(targets))}
function slug(s){return s.replace(/-/g,' ')}
function regionFor(id){let r=regions.find(x=>id>=x[1]&&id<=x[2]);return r?r[0]:(id>=899&&id<=905?'Hisui':'—')}
function formatName(s){return slug(s).replace(/\b\w/g,c=>c.toUpperCase())}
async function init(){
 try{
  const cached=localStorage.getItem('pogoSpeciesCache');
  if(cached) pokemon=JSON.parse(cached); else {
   const res=await fetch('https://pokeapi.co/api/v2/pokemon-species?limit=1025&offset=0');
   const data=await res.json(); pokemon=data.results.map((p,i)=>({id:i+1,name:p.name,region:regionFor(i+1)})); localStorage.setItem('pogoSpeciesCache',JSON.stringify(pokemon));
  }
  document.getElementById('statusText').textContent=`${pokemon.length} espécies carregadas. Seus dados ficam neste navegador.`;
  buildRegions(); buildTargets(); renderAll();
 }catch(e){document.getElementById('statusText').textContent='Não foi possível carregar a Pokédex. Conecte-se à internet e recarregue.'}
}
function entry(id){return collection[id]||{normal:0,shiny:0,shadow:0,regional:0,xxl:0,xxs:0,male:0,female:0,lucky:0,fourStar:0,notes:''}}
function owned(id){const e=entry(id);return Object.values(e).slice(0,10).some(v=>Number(v)>0)}
function buildRegions(){const s=document.getElementById('regionFilter');s.innerHTML='<option value="all">Todas as regiões</option>'+[...new Set(pokemon.map(p=>p.region))].filter(Boolean).map(r=>`<option>${r}</option>`).join('')}
function buildTargets(){const labels={normal:'Pokémon / espécies',shiny:'Shiny',shadow:'Shadow',regional:'Regionais',xxl:'XXL',xxs:'XXS',male:'Macho',female:'Fêmea',lucky:'Lucky',fourStar:'4★'};document.getElementById('targetFields').innerHTML=Object.entries(labels).map(([k,v])=>`<div class="target"><label>${v}</label><input type="number" min="0" data-target="${k}" value="${targets[k]??0}"></div>`).join('')}
function total(field){return pokemon.reduce((n,p)=>n+Number(entry(p.id)[field]||0),0)}
function speciesOwned(){return pokemon.filter(p=>owned(p.id)).length}
function metric(label,field,target){const n=field==='normal'?speciesOwned():total(field);const t=targets[target||field]??0;const pct=t?Math.min(100,n/t*100):0;return `<div class="card"><div class="label">${label}</div><div class="value">${n.toLocaleString('pt-BR')}</div><div class="sub">de ${t.toLocaleString('pt-BR')} • ${pct.toFixed(1)}%</div></div>`}
function renderDashboard(){const cards=document.getElementById('metricCards');cards.innerHTML=metric('Pokémon registrados','normal')+metric('✨ Shiny','shiny')+metric('👻 Shadow','shadow')+metric('🌎 Regionais','regional')+metric('⬆️ XXL','xxl')+metric('⬇️ XXS','xxs');const pct=targets.normal?Math.min(100,speciesOwned()/targets.normal*100):0;document.getElementById('overallPct').textContent=pct.toFixed(1)+'%';
 document.getElementById('regionProgress').innerHTML=regions.concat([['Hisui',899,905]]).map(([name,a,b])=>{const list=pokemon.filter(p=>p.id>=a&&p.id<=b);if(!list.length)return '';const have=list.filter(p=>owned(p.id)).length;const pc=have/list.length*100;return `<div class="regionRow"><div class="regionLine"><b>${name}</b><span>${have} / ${list.length} (${pc.toFixed(1)}%)</span></div><div class="bar"><i style="width:${pc}%"></i></div></div>`}).join('');
 document.getElementById('summary').innerHTML=[['Total de espécies',pokemon.length],['Espécies que você possui',speciesOwned()],['Pokémon normais (quantidade)',total('normal')],['Macho',total('male')],['Fêmea',total('female')],['Lucky',total('lucky')],['4★',total('fourStar')]].map(x=>`<div class="summaryRow"><span>${x[0]}</span><b>${x[1].toLocaleString('pt-BR')}</b></div>`).join('')}
function renderDex(){const q=document.getElementById('search').value.toLowerCase().trim(),r=document.getElementById('regionFilter').value,f=document.getElementById('statusFilter').value;let list=pokemon.filter(p=>{const e=entry(p.id);if(r!=='all'&&p.region!==r)return false;if(q&&!(`${p.id}`.includes(q)||p.name.includes(q)))return false;if(f==='owned'&&!owned(p.id))return false;if(f==='missing'&&owned(p.id))return false;if(f!=='all'&&['owned','missing'].indexOf(f)<0&&Number(e[f]||0)<=0)return false;return true});document.getElementById('dexCounter').textContent=`${list.length} / ${pokemon.length}`;document.getElementById('pokemonGrid').innerHTML=list.map(p=>{const e=entry(p.id);return `<article class="pokeCard" onclick="openPokemon(${p.id})"><div class="pokeTop"><span>#${String(p.id).padStart(4,'0')}</span><span class="ownedDot ${owned(p.id)?'on':''}"></span></div><div class="pokeMain"><img loading="lazy" src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${p.id}.png" onerror="this.style.visibility='hidden'"><div><div class="pokeName">${formatName(p.name)}</div><div class="pokeRegion">${p.region}</div></div></div><div class="miniStats"><span>Normal ${e.normal||0}</span><span>✨ ${e.shiny||0}</span><span>👻 ${e.shadow||0}</span><span>XXL ${e.xxl||0}</span><span>XXS ${e.xxs||0}</span><span>♂ ${e.male||0} / ♀ ${e.female||0}</span></div></article>`}).join('')}
function renderAll(){renderDashboard();renderDex()}
function openPokemon(id){const p=pokemon.find(x=>x.id===id),e=entry(id);const fields=[['normal','Normal'],['shiny','✨ Shiny'],['shadow','👻 Shadow'],['regional','🌎 Regional'],['xxl','⬆️ XXL'],['xxs','⬇️ XXS'],['male','♂ Macho'],['female','♀ Fêmea'],['lucky','🍀 Lucky'],['fourStar','4★']];document.getElementById('modalContent').innerHTML=`<div class="detailHead"><img src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png"><div><span class="eyebrow">#${String(id).padStart(4,'0')} • ${p.region}</span><h2>${formatName(p.name)}</h2><p>Informe quantos você possui em cada categoria.</p></div></div><div class="detailGrid">${fields.map(([k,l])=>`<div class="detailItem"><label>${l}</label><input type="number" min="0" data-field="${k}" value="${e[k]||0}"></div>`).join('')}</div><div class="detailItem" style="margin-top:12px"><label>Observações</label><input data-field="notes" value="${(e.notes||'').replace(/"/g,'&quot;')}"></div><div class="saveRow"><button class="primary" onclick="savePokemon(${id})">Salvar</button></div>`;document.getElementById('modal').classList.remove('hidden')}
function savePokemon(id){const e=entry(id);document.querySelectorAll('#modalContent [data-field]').forEach(el=>e[el.dataset.field]=el.dataset.field==='notes'?el.value:Math.max(0,parseInt(el.value||0)));collection[id]=e;save();document.getElementById('modal').classList.add('hidden');renderAll();toast('Pokémon salvo.')}
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
function backup(){const payload={app:'Pokemon GO Collection Tracker',version:1,createdAt:new Date().toISOString(),targets,collection};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pokemon-go-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);document.getElementById('lastBackup').textContent='Último backup: '+new Date().toLocaleString('pt-BR');toast('Backup criado.')}
function restore(file){const reader=new FileReader();reader.onload=()=>{try{const p=JSON.parse(reader.result);if(!p.collection)throw Error();collection=p.collection;targets={...defaultTargets,...(p.targets||{})};save();saveTargets();buildTargets();renderAll();toast('Backup restaurado.')}catch{toast('Arquivo de backup inválido.')}};reader.readAsText(file)}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(b.dataset.view).classList.add('active')});['search','regionFilter','statusFilter'].forEach(id=>document.getElementById(id).addEventListener('input',renderDex));document.getElementById('backupBtn').onclick=backup;document.getElementById('restoreBtn').onclick=()=>document.getElementById('restoreInput').click();document.getElementById('restoreInput').onchange=e=>e.target.files[0]&&restore(e.target.files[0]);document.getElementById('closeModal').onclick=()=>document.getElementById('modal').classList.add('hidden');document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.add('hidden')};document.getElementById('saveTargets').onclick=()=>{document.querySelectorAll('[data-target]').forEach(i=>targets[i.dataset.target]=Math.max(0,parseInt(i.value||0)));saveTargets();renderAll();toast('Metas salvas.')};init();
</script>
